services:
  - type: web
    name: bookstore-tri-thuc-java-20261005
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /login
    envVars:
      - key: BOOKSTORE_DB_URL
        sync: false
      - key: BOOKSTORE_DB_USER
        sync: false
      - key: BOOKSTORE_DB_PASSWORD
        sync: false
      - key: BOOKSTORE_SMTP_EMAIL
        sync: false
      - key: BOOKSTORE_SMTP_APP_PASSWORD
        sync: false
